### ISSUE TITLE
[Feature] - Add possibility to delete specific item from the list of items

### ISSUE THREAD

**Issue by saifabusaleh** [saifabusaleh/clipboard-history-extension#8]
Currently its only possible to clear all the list of the items
![image](https://user-images.githubusercontent.com/15147809/95380330-456e6200-08ef-11eb-97a5-e4693936ad3c.png)

Add the possibility to remove specific items from it

Tasks:

1- Add in the UI [x] icon in each item, Icon color should change depending on theme (white theme, dark theme)

2- add to chrome storage items option that makes it possible to delete specific item
One option is to update the data structure to map and when removing to remove by key

3- connect it in the javascript so when clicking on it it will delete the item

Follow the readme getting started for more info how to contribute

**Comment by zurda** [comment]
Hi there @saifabusaleh, really awesome project. I'd love to get involved.
Is it OK if I take this issue?

**Comment by saifabusaleh** [comment]
Hi @zurda ,

Sure go ahead

You can also do changes to the UX item layout if necessary after adding the icon

Also its better if you add it as svg instead of normal image button

**Comment by zurda** [comment]
Sure thing, thanks! 
If you have any other pointers feel free to add here. I'll let you know if I have any questions, but it seems straightforward.

**Comment by saifabusaleh** [comment]
hi @zurda 

I have updated the description of the issue

To be able to delete specific item, need a way to link the selected item with saved chrome storage items


Let me know if you need any help

**Comment by zurda** [comment]
Hi @saifabusaleh , I've created a PR for this: https://github.com/saifabusaleh/clipboard-history-extension/pull/11
I ended up using the letter 'X' rather than an SVG. If you had an SVG you wanted to use please feel free to add it here and I'm happy to add it instead. 

Thanks for the opportunity to work on this project - it was really nice to explore chrome extensions, and can't wait to see where you take this :)

**Comment by zurda** [comment]
Hi @saifabusaleh , I've created a PR for this: https://github.com/saifabusaleh/clipboard-history-extension/pull/11
I ended up using the letter 'X' rather than an SVG. If you had an SVG you wanted to use please feel free to add it here and I'm happy to add it instead. 

Thanks for the opportunity to work on this project - it was really nice to explore chrome extensions, and can't wait to see where you take this :)

**Comment by saifabusaleh** [comment]
> Hi @saifabusaleh , I've created a PR for this: #11
> I ended up using the letter 'X' rather than an SVG. If you had an SVG you wanted to use please feel free to add it here and I'm happy to add it instead.
> 
> Thanks for the opportunity to work on this project - it was really nice to explore chrome extensions, and can't wait to see where you take this :)

Hi, Thanks for contribution 🥇 

I reviewed the PR and added few comments, other than that the rest looks good

Also I will try to search for SVG and update it here

Thanks 👍

**Comment by zurda** [comment]
PR should be ready for review again  👍

**Comment by saifabusaleh** [comment]
Hi @zurda ,

I checked the code and it looks good, thanks

I found SVG, you can use this: 
`<svg height="16" class="octicon octicon-x" viewBox="0 0 16 16" version="1.1" width="16" aria-hidden="true"><path fill-rule="evenodd" d="M3.72 3.72a.75.75 0 011.06 0L8 6.94l3.22-3.22a.75.75 0 111.06 1.06L9.06 8l3.22 3.22a.75.75 0 11-1.06 1.06L8 9.06l-3.22 3.22a.75.75 0 01-1.06-1.06L6.94 8 3.72 4.78a.75.75 0 010-1.06z"></path></svg>`

You can change the `width` and `height` as you wish so it fit the UI

**Comment by zurda** [comment]
I put the SVG in, should be ready for review again

**Comment by saifabusaleh** [comment]
Closed by #13
